services:
  oracle-xe:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle-xe
    restart: always
    environment:
      - ORACLE_PWD=123456
      - ORACLE_CHARACTERSET=AL32UTF8
    ports:
      - "1522:1521"
      - "5500:5500"
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./bankdb/BANK_USER_DUMP.DMP:/opt/oracle/admin/XE/dpdump/BANK_USER_DUMP.DMP

volumes:
  oracle_data:

