CREATE USER C##BANK_USER IDENTIFIED BY askljnobbDSAi12sSda;
ALTER USER C##BANK_USER QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE, DBA TO C##BANK_USER;
GRANT UNLIMITED TABLESPACE TO C##BANK_USER;

